version: '2'
services:
  jenkins-primary:
    image: "jenkins:2.19.4"
    ports:
      - "8081:8080"
    labels:
      io.rancher.sidekicks: jenkins-plugins,jenkins-datavolume
      io.rancher.container.hostname_override: container_name
    volumes_from:
      - jenkins-plugins
      - jenkins-datavolume
    entrypoint: /usr/share/jenkins/rancher/jenkins.sh
  jenkins-plugins:
    image: rancher/jenkins-plugins:v0.1.1
  jenkins-datavolume:
    image: "busybox"
    volumes:
      - /var/lib/docker/jenkins-ci:/var/jenkins_home
    labels:
      io.rancher.container.start_once: true
    entrypoint: ["chown", "-R", "1000:1000", "/var/jenkins_home"]
tomcat:
  image: "evroon/tomcat:practice-lab"
  ports:
    - "8082:8080"
